name: Build and check validity of traces

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip3 install jsonschema
          pip3 install requests
      - name: Check validity of traces
        run: |
          find . -type f -name "*.json" > traces.txt && err=0
          git clone https://github.com/workflowhub/workflow-schema
          for trace_file in `cat traces.txt`; do
            python3 ./workflow-schema/workflowhub-validator.py -d ${trace_file};
            (( err += $? ));
            echo "";
          done
          if [ $err -ne 0 ]; then
            echo "The verification failed for ${err} trace files.";
            exit 1;
          fi
